PHP-174 Unit tests
lamoda/codeception-flysystem pull request #2
Opened 2019-01-11 13:53 UTC by AntonTrekov

2019-01-13 12:57 UTC, AntonTrekov commented
Changed branch name and fixed grammar error in method names

2019-01-16 14:30 UTC, pavelsavelyev commented on src/Extension/FileSystem.php
> +    public function grabFileList($path = '')
зачем это?

2019-01-16 19:29 UTC, AntonTrekov commented on src/Extension/FileSystem.php
> +    public function grabFileList($path = '')
Во всем файле используется такое в методах. Чтобы можно было использовать метод без аргументов, привести к единому стилю с остальными.

2019-01-17 07:49 UTC, Tekill requested changes

2019-01-17 07:49 UTC, Tekill commented on src/Extension/FlySystemModule.php
>              $message = sprintf('Unexpected error happened on creation adapter factory, %s', $className);
```suggestion
            $message = sprintf('Adapter %s does not exist, please use another one', $className);
```

2019-01-17 07:49 UTC, Tekill commented on tests/_support/Helper/Unit.php
> +    public function getProtectedProperty($object, $propertyName)
В юнит тесте, зачем? Для чего пришлось такое придумать? Тестируются же публичные методы только

2019-01-17 07:49 UTC, Tekill commented on src/Extension/FileSystem.php
> +    public function grabFileList($path = '')
> Во всем файле используется такое в методах. Чтобы можно было использовать метод без аргументов, привести к единому стилю с остальными.

Нашел только в 2 местах, в ассертах. Все равно не понятно, как можно запросить получение списка файлов у пустого пути. Нужно явно указывать путь

2019-01-17 08:36 UTC, AntonTrekov commented on tests/_support/Helper/Unit.php
> +    public function getProtectedProperty($object, $propertyName)
Хотел проверить, что в модуле все правильно собирается. Я, конечно, могу добавить публичный метод `::getFlySystem()` и его протестировать, но не хочу это делать.

2019-01-17 08:40 UTC, AntonTrekov commented on src/Extension/FileSystem.php
> +    public function grabFileList($path = '')
Интерфейс `League\Flysystem\FilesystemInterface` может работать без параметра. Пустая строка как раз ставится у тех методов, который используют этот метод. Получается, что у них можно не указывать путь, а у этого будет нельзя (хотя по факту можно, но мы не везде разрешаем)

2019-01-21 07:40 UTC, Tekill commented on src/Extension/FileSystem.php
> +    public function grabFileList($path = '')
Все равно ничего не понял :) Открыл `League\Flysystem\FilesystemInterface`, а там везде `$path` обязателен

2019-01-21 07:43 UTC, Tekill approved these changes
Все равно не понял ничего с `$path = ''`, но это неважный пункт

2019-01-21 19:21 UTC, AntonTrekov commented on src/Extension/FileSystem.php
> +    public function grabFileList($path = '')
В `::listContents($directory = '', $recursive = false)` как раз необязателен

2019-01-22 11:22 UTC, merged